Msgbox"He is a hustler, he`s no good at all",0+-1,""
Msgbox"He is a loser, he`s a bum, bum, bum, bum",0+-1,""
Msgbox"He lies, he bluffs, he`s unreliable",0+-1,""
Msgbox"He is a sucker with a gun, gun, gun, gun",0+-1,""
Msgbox"I know you told I should stay away",0+-1,""
Msgbox"I know you said he`s a dog astray",0+-1,""
Msgbox"He is a bad boy with a tainted heart",0+-1,""
Msgbox"And even I know this ain`t smart",0+-1,""
Msgbox"But mama im in love with a criminal",0+-1,""
Msgbox"And this type of love isn`t rational, it`s physical",0+-1,""
Msgbox"Mama please don`t cry, I will be alright ",0+-1,""
Msgbox"All reason aside I just can`t deny, I love the guy ",0+-1,""
Msgbox"He is a villan by the devil`s law",0+-1,""
Msgbox"He is a killer just for fun, fun, fun, fun",0+-1,""
Msgbox"That man`s a snitch and unpredictable",0+-1,""
Msgbox"He`s got no conscience, got none, none, none, none ",0+-1,""
Msgbox"All I know, should`ve let go, but no",0+-1,""
Msgbox"Cause he is a bad boy with a tainted heart",0+-1,""
Msgbox"And even I know this ain`t smart",0+-1,""
Msgbox"But mama im in love with a criminal",0+-1,""
Msgbox"And this type of love isn`t rational, it`s physical",0+-1,""
Msgbox"Mama please don`t cry, I will be alright",0+-1,""
Msgbox"All reason aside I just can`t deny, I love the guy",0+-1,""
Msgbox"And he`s got my name",0+-1,""
Msgbox"Tattooed on his arm his lucky charm",0+-1,""
Msgbox"So I guess it`s okay he`s with me",0+-1,""
Msgbox"And I hear people talk",0+-1,""
Msgbox"Trying to make remarks keep us apart",0+-1,""
Msgbox"But I don`t even hear",0+-1,""
Msgbox"I don`t care",0+-1,""
Msgbox"Cause mama im in love with a criminal",0+-1,""
Msgbox"And this type of love isn`t rational, it`s physical",0+-1,""
Msgbox"Mama please don`t cry, I will be alright",0+-1,""
Msgbox"All reason aside I just can`t deny, I love the guy",0+-1,""
Msgbox"Mama I`m in love with a criminal",0+-1,""
Msgbox"And this type of love isn`t rational, it`s physical",0+-1,""
Msgbox"Mama please don`t cry, I will be alright",0+-1,""
Msgbox"All reason aside I just can`t deny, I love the guy",0+-1,""





